### ISSUE TITLE
 get_class() expects parameter 1 to be object, int given

### ISSUE THREAD

**Issue by Beakerboy** [TenthPres/MyTotalComfort#1]
Warning: get_class() expects parameter 1 to be object, int given in tenth/my-total-comfort/src/MyTotalComfort.php on line 186

**Comment by jkrrv** [comment]
Definitely going to need more information to diagnose this problem.  What are you trying to do?

**Comment by Beakerboy** [comment]
The php get_class function requires an object. The getZonesByLocation function says it accepts an optional int or object. If it is null, it looks up the appropriate int. If an int is provided, it will call get_class with the int as the parameter, creating the above error. Changing it to:

if (is_object($location) && get_class($location) 

Will fix it.

**Comment by Beakerboy** [comment]
Also...I would love to see an example of how this is supposed to work. I’m trying to poll my thermostat so I can save values to a database or flat file and then get a graph of home temp and setpoint overnight to troubleshoot a problem. I assume this object will be able to get the current temp and setpoint...bonus points if it gives the outside temp too.

**Comment by Beakerboy** [comment]
As an aside, I was short in my description because I was assuming you would be like most people on GitHub and never respond. I was going to submit a pull request and reference this issue in case anyone else used this library. Thanks for the speedy response.

**Comment by jkrrv** [comment]
This library was built for a thing that's crucial for me at work, so, relatively speaking, yeah, I care about bugs.  You're welcome to submit the PR; I won't get to fixing this myself for a day or two. 

Whether or not it can get the outside temp depends on which thermostat model you have.  

To briefly clarify terms: "Location" and "Zone" are the terms Honeywell uses in the urls of their web interface.  (e.g. [Locations](https://www.mytotalconnectcomfort.com/portal/Locations))  Zones ≈ Thermostats

To do what you're describing, I'd do something like: 


    $cookieJar = new \GuzzleHttp\Cookie\FileCookieJar(__DIR__ . 'cookie_jar.txt', true);
    $tcc = new \Tenth\MyTotalComfort(EMAIL, PASSWORD, $cookieJar);
    $z = $tcc->getZone(ZONE_ID);
    echo $z->dispTemperature;  // prints the "display temperature"


EMAIL and PASSWORD is pretty self-explanatory, but ZONE_ID is the identifier you can see in the URL for the web interface in the format https://www.mytotalconnectcomfort.com/portal/Device/Control/ZONE_ID

If I were doing it, I would *not* have it iterate over the list of Zones because, depending on how many zones you have, that could mean this thing has to make several different requests just to generate the list, and Honeywell returns those requests kinda slowly.  You're better off, therefore, storing a list of known zone IDs and just requesting those directly, as I did in the example.

**Comment by Beakerboy** [comment]
Thanks. I only have one zone, and I'm in the "how does thing thing work" phase. I'll optimize it as I work through the process. 

When I log into the website, it does display the outsize temp, But I've always assumed this was fetched by honeywell from the national weather service or the weather.com API on their end. I'm pretty sure I do not have an RTD on the exterior of the home.

**Comment by Beakerboy** [comment]
$tcc->getZone(ZONE_ID); requires two parameters. This line gives an error.

**Comment by jkrrv** [comment]
mmmm Looks like I haven't pushed my commits in a little while.  Sorry about that... 

Pass an empty array as the second parameter (on my newer commits, that's a default value). 

e.g. `$tcc->getZone(ZONE_ID, [])`
