### ISSUE TITLE
Notice:  Undefined offset: 0 in tenth/my-total-comfort/src/MyTotalComfort.php on line 125

### ISSUE THREAD

**Issue by Beakerboy** [TenthPres/MyTotalComfort#2]
Calling library like this:

```php
$object = new MyTotalComfort("xxxx", "xxxx");
$locations = $object->getLocations();
foreach ($locations as $location) {
    $zones = $location->getZones();
    foreach ($zones as $zone) {
        echo $zone['dispTemp'];
    }
}
```

**Comment by jkrrv** [comment]
Which line is 125?  My guess here is that Guzzle isn't maintaining the state (cookies) between requests.  There's a lot of variance between server configurations (and use cases) that affect how exactly Guzzle does its thing.  You'll note in my example in #1 that I included a bit to save the cookies to a text file, which is probably the quick and easy way to do it.  In my own application, I have them saved to a database. 

Also, the Zones are meant to be treated as objects, so `$zone->dispTemp` instead of the array format `$zone['dispTemp']`

**Comment by Beakerboy** [comment]
Since you have a __get() magic function defined, I assumed that was the preferred method.

Line 125 is:

    $this->defaultLocationId = $locIdMatches[0];

in getLocations()

**Comment by jkrrv** [comment]
Yeah, still pretty sure Guzzle isn't maintaining the state...

**Comment by Beakerboy** [comment]
Setting the cookie jar as you suggested took care of this.

**Comment by Beakerboy** [comment]
Adding the cookie jar got my original code to work, but passing in the empty array just returns nothing.

**Comment by Beakerboy** [comment]
If I'm reading the code correctly, all the data from this library is read from the zonelist page, and not the thermostat control page, right? The thermostat control page has a list of Control.Model.Property assignments that seems to include setpoints and local weather. any plans on using that as the data source?

**Comment by jkrrv** [comment]
sure. a149dc1 is for you.   BUT, if the thermostat doesn't display an outdoor temperature/humidity on the screen, it's going to return 128 as the values. 

I'm not really motivated to go through the workarounds that are used on the web interface for other models because there are a lot of better APIs out there for asking the internet what the conditions are outside.

**Comment by Beakerboy** [comment]
I added this to Zone.php
```php
 public function getWeather()
    {
        $r = $this->context->request('GET', '/portal/Device/Control/' . $this->id, [
                'headers' => [
                    'Origin' => 'https://www.mytotalconnectcomfort.com/',
                    'Referer' => 'https://www.mytotalconnectcomfort.com/portal/Device/Control/' . $this->id,
                    'Host' => 'www.mytotalconnectcomfort.com',
                    'Content-Type' => 'application/json; charset=UTF-8',
                    'Upgrade-Insecure-Requests' => 1,
                    'User-Agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36',
                    'Accept' => 'application/json, text/javascript, */*; q=0.01',
                    'Accept-Encoding' => 'gzip, deflate, br',
                    'Cache-Control' => 'no-cache',
                    'DNT' => '1',
                    'X-Requested-With' => 'XMLHttpRequest'
                ]
            ]);
        $matches = [];
        $rule = "/Control\.Model\.Property\.weatherTemperature, '(..?)'/";
        $weather = preg_match($rule, $r->getBody(), $matches);
        return $matches[1];
    }
```

**Comment by jkrrv** [comment]
Cool.  Obviously, that works, but it does add the overhead of the additional request.  If that's not a problem for you, then great!  It just doesn't scale well--especially since the information will be the same for all zones in a given location.  

Glad it works for you, though!

**Comment by Beakerboy** [comment]
If a user just requests one zone, sending the request to /portal/Device/Control/{ID} would have the same overhead as polling the Zone list, with the added benefit of accessing more data.
